num1 = int(input('enter num1: '))
num2 = int(input('enter num2: '))

the_result = num1 + num2

product = num1 * num2

quotient = num1 / num2

print('the sum is', the_result)
print('the product is', product)
print('the quotient is', quotient)

